CITY_TRANSLATIONS = {
    "москва": "moskva",
    "мск": "moskva",
    "спб": "sankt-peterburg",
    "питер": "sankt-peterburg",
    "санкт-петербург": "sankt-peterburg",
    "новосибирск": "novosibirsk",
    'новосиба':"novosibirsk",
    "екатеринбург": "ekaterinburg",
    "казань": "kazan",
    "нижний новгород": "nizhniy_novgorod",
    "ростов": "rostov-na-donu",
    "ростов-на-дону": "rostov-na-donu",
    "владивосток": "vladivostok",
    'владик': 'vladivostok',
    "краснодар": "krasnodar",
    "самара": "samara",
    "омск": "omsk",
    "челябинск": "chelyabinsk",
    'челяба': "chelyabinsk",
    "уфа": "ufa",
    'махачкала': 'mahachkala',
    'мах': 'mahachkala',
    'маха': 'mahachkala',
    'нальчик': 'nalchik',
    'грозный': 'groznyy'
}