CITY_TRANSLATIONS = {
    "москва": "moskva",
    "мск": "moskva",
    "спб": "sankt-peterburg",
    "питер": "sankt-peterburg",
    "санкт-петербург": "sankt-peterburg",
    "новосибирск": "novosibirsk",
    "екатеринбург": "ekaterinburg",
    "казань": "kazan",
    "нижний новгород": "nizhniy_novgorod",
    "ростов": "rostov-na-donu",
    "ростов-на-дону": "rostov-na-donu",
    "владивосток": "vladivostok",
    "краснодар": "krasnodar",
    "самара": "samara",
    "омск": "omsk",
    "челябинск": "chelyabinsk",
    "уфа": "ufa",
}